# Generated by Django 5.0.1 on 2024-05-22 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=100, unique=True)),
                ('password', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OSTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='VPSTypeTemplate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('price', models.IntegerField()),
                ('VPSType', models.CharField(max_length=200)),
                ('status', models.IntegerField()),
                ('paymentMethod', models.CharField(max_length=100)),
                ('createAt', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('targetVPS', models.CharField(max_length=20, null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='VPS',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=10)),
                ('CPU', models.IntegerField()),
                ('RAM', models.IntegerField()),
                ('SSD', models.IntegerField()),
                ('price', models.IntegerField()),
                ('expired_date', models.DateTimeField()),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.IntegerField()),
                ('OS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.ostemplate')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='VPSTemplate',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('CPU', models.IntegerField()),
                ('RAM', models.IntegerField()),
                ('SSD', models.IntegerField()),
                ('pricePerMonth', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vpstypetemplate')),
            ],
        ),
    ]
