# Generated by Django 5.0.1 on 2024-05-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=100, unique=True)),
                ('password', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.TextField(blank=True, max_length=20)),
            ],
        ),
    ]
